"""agent/data/metrics.py

OpenTelemetry metrics setup for the HR AI Agent.
Provides structured counters for DAB operations, chart generation, and error tracking.
"""
import os
import logging
from typing import Optional

logger = logging.getLogger("hr_agent")

# ── OpenTelemetry Meter (lazy init) ─────────────────────────────────────────
_meter = None


def _get_meter():
    """Lazy-initialize the OpenTelemetry meter."""
    global _meter
    if _meter is not None:
        return _meter

    try:
        from opentelemetry.metrics import get_meter
        service_name = os.getenv("OTEL_SERVICE_NAME", "hr-ai-agent")
        _meter = get_meter(service_name)
        logger.info("OpenTelemetry metrics initialized for service=%s", service_name)
    except Exception as e:
        logger.warning("OpenTelemetry metrics init failed: %s", e)
        _meter = _NullMeter()
    return _meter


class _NullMeter:
    """No-op meter fallback when OpenTelemetry is unavailable."""

    class _NullCounter:
        def add(self, *args, **kwargs):
            pass

    class _NullHistogram:
        def record(self, *args, **kwargs):
            pass

    def create_counter(self, *args, **kwargs):
        return self._NullCounter()

    def create_histogram(self, *args, **kwargs):
        return self._NullHistogram()


# ── Metric helpers ──────────────────────────────────────────────────────────

def _get_counter(name: str, description: str, unit: str = "1"):
    """Get or create a counter."""
    meter = _get_meter()
    return meter.create_counter(name, unit=unit, description=description)


# DAB tool call counter
dab_tool_call_counter = None

def get_dab_tool_call_counter():
    global dab_tool_call_counter
    if dab_tool_call_counter is None:
        dab_tool_call_counter = _get_counter(
            "dab_tool_calls",
            "Number of DAB tool calls by tool name and result status"
        )
    return dab_tool_call_counter


# DAB error counter
dab_error_counter = None

def get_dab_error_counter():
    global dab_error_counter
    if dab_error_counter is None:
        dab_error_counter = _get_counter(
            "dab_errors",
            "Number of DAB errors by error type"
        )
    return dab_error_counter


# Chart generation counter
chart_generated_counter = None

def get_chart_generated_counter():
    global chart_generated_counter
    if chart_generated_counter is None:
        chart_generated_counter = _get_counter(
            "charts_generated",
            "Number of charts generated by chart type and mode"
        )
    return chart_generated_counter


# Entity normalization counter
entity_normalized_counter = None

def get_entity_normalized_counter():
    global entity_normalized_counter
    if entity_normalized_counter is None:
        entity_normalized_counter = _get_counter(
            "entity_name_normalized",
            "Number of entity name normalizations by normalization type"
        )
    return entity_normalized_counter


# ── Convenience wrappers ─────────────────────────────────────────────────────

def record_dab_tool_call(tool: str, status: str):
    """Record a DAB tool call with status label."""
    counter = get_dab_tool_call_counter()
    counter.add(1, {"tool": tool, "status": status})


def record_dab_error(error_type: str, entity: Optional[str] = None):
    """Record a DAB error with type label."""
    counter = get_dab_error_counter()
    labels = {"error_type": error_type}
    if entity:
        labels["entity"] = entity
    counter.add(1, labels)


def record_chart_generated(chart_type: str, mode: str):
    """Record a chart generation."""
    counter = get_chart_generated_counter()
    counter.add(1, {"chart_type": chart_type, "mode": mode})


def record_entity_normalized(normalization_type: str, original: str, corrected: str):
    """Record an entity name normalization."""
    counter = get_entity_normalized_counter()
    counter.add(1, {
        "type": normalization_type,
        "original": original,
        "corrected": corrected
    })
