"""
Export service for the agentic executor.

Encapsulates all Excel-export concerns:
  - Metadata construction for provenance/audit
  - Filename prefix derivation
  - Chart-rich export (primary path)
  - Data-only export fallback (privacy-constrained or chart-blocked paths)
"""
import logging
from typing import Any, Dict, List, Optional

from agent.data.response import extract_items
from agent.data.metrics import record_chart_generated
from agent.output.excel_exporter import export_to_excel, export_to_excel_with_chart
from agent.auth.role_resolver import is_data_about_user


logger = logging.getLogger("hr_agent")


def derive_export_prefix(chart_config: Optional[dict], entity: str = "") -> str:
    """Generate a human-readable filename prefix from data context, not user query.

    Derives semantic name from:
      1. chart_config.x_column (e.g., "job_level" -> "job_level")
      2. chart_config.type (e.g., "pie" -> "pie_chart")
      3. Entity name fallback (e.g., "Employees" -> "employee")

    Returns snake_case string suitable for filenames.
    """
    parts: List[str] = []

    if chart_config and isinstance(chart_config, dict):
        x_col = chart_config.get("x_column", "")
        chart_type = chart_config.get("type", "")

        if x_col:
            parts.append(x_col.lower().replace(" ", "_"))
        elif entity:
            parts.append(entity.lower().rstrip("s"))

        if chart_type and chart_type not in ("bar", "table"):
            parts.append(chart_type.lower())
        elif chart_type == "bar":
            parts.append("distribution")
    elif entity:
        parts.append(entity.lower().rstrip("s"))

    if not parts:
        parts.append("export")

    return "_".join(parts)


def build_export_metadata(
    chart_config: Optional[dict],
    auth_context: Any,
    auth_role: str,
    user_query: str,
    intent_result: Any,
    tool_calls_made: List[Dict],
) -> Dict[str, str]:
    """Build metadata dict for Excel workbook properties."""
    metadata = {
        "Report": chart_config.get("title", "HR Analytics Report") if chart_config else "HR Analytics Report",
        "Generated": _now_str(),
        "Tenant": getattr(auth_context, "tenant_id", "LOCALDEV") if auth_context else "LOCALDEV",
        "Generated By": getattr(auth_context, "email", "system") if auth_context else "system",
        "User Role": auth_role,
        "Query": user_query,
        "Intent": getattr(intent_result, "intent", "unknown"),
        "Data Scope": getattr(intent_result, "data_scope", "unknown"),
        "Chart Type": chart_config.get("type", "bar") if chart_config else "none",
        "X Column": chart_config.get("x_column", "") if chart_config else "",
        "Y Column": chart_config.get("y_column", "") if chart_config else "",
        "AI Version": "Prototype Agent 0.1",
        "Source": "hana-mcp-server",
    }

    if tool_calls_made:
        tc = tool_calls_made[0]
        args = tc.get("args", {})
        if args.get("filter"):
            metadata["Filters Applied"] = str(args["filter"])
        if args.get("entity"):
            metadata["Entity"] = args["entity"]

    return metadata


def generate_chart_export(
    chartable_data: List[Dict],
    chart_config: dict,
    auth_role: str,
    metadata: Dict[str, str],
    tool_calls_made: List[Dict],
) -> Optional[str]:
    chart_type = chart_config.get("type", "bar")
    x_col = chart_config.get("x_column")
    y_col = chart_config.get("y_column")
    title = chart_config.get("title")

    tc = tool_calls_made[0] if tool_calls_made else {}
    prefix = derive_export_prefix(chart_config, tc.get("args", {}).get("entity", ""))

    export_url = export_to_excel_with_chart(
        data=chartable_data,
        chart_type=chart_type,
        x_column=x_col,
        y_column=y_col,
        title=title,
        prefix=prefix or "export",
        auth_role=auth_role,
        metadata=metadata,
    )
    if export_url:
        record_chart_generated(chart_type, "excel")
        logger.info("EXECUTOR_EXPORT: generated Excel chart export: %s", export_url)
        return export_url

    logger.warning(
        "EXECUTOR_EXPORT: chart export blocked or failed (privacy/role/invalid data). "
        "Falling back to data-only export."
    )
    return None


def generate_data_export(items: List[Dict], strict_privacy: bool) -> Optional[str]:
    export_url = export_to_excel(items, prefix="full_profile", strict_privacy=strict_privacy)
    if export_url:
        logger.info("EXECUTOR_FULLINFO_EXPORT: generated data-only Excel export for %d records: %s", len(items), export_url)
    return export_url


def _now_str() -> str:
    from datetime import datetime
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
